# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GraphsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BaseWindow(object):
    def setupUi(self, BaseWindow):
        BaseWindow.setObjectName("BaseWindow")
        BaseWindow.resize(550, 660)
        BaseWindow.setMinimumSize(QtCore.QSize(550, 660))
        BaseWindow.setMaximumSize(QtCore.QSize(550, 660))
        BaseWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BaseWidget = QtWidgets.QWidget(BaseWindow)
        self.BaseWidget.setStyleSheet("background-color: rgb(250, 245, 230);")
        self.BaseWidget.setObjectName("BaseWidget")
        self.functionInput = QtWidgets.QLineEdit(self.BaseWidget)
        self.functionInput.setGeometry(QtCore.QRect(150, 20, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.functionInput.setFont(font)
        self.functionInput.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 13pt \"Segoe Print\";")
        self.functionInput.setInputMask("")
        self.functionInput.setMaxLength(32766)
        self.functionInput.setObjectName("functionInput")
        self.calcButton = QtWidgets.QLabel(self.BaseWidget)
        self.calcButton.setGeometry(QtCore.QRect(240, 570, 55, 71))
        self.calcButton.setText("")
        self.calcButton.setPixmap(QtGui.QPixmap("images.png"))
        self.calcButton.setObjectName("calcButton")
        self.askButton = QtWidgets.QLabel(self.BaseWidget)
        self.askButton.setGeometry(QtCore.QRect(10, 80, 61, 61))
        self.askButton.setText("")
        self.askButton.setPixmap(QtGui.QPixmap("questionSign.png"))
        self.askButton.setObjectName("askButton")
        self.functionInput_2 = QtWidgets.QLineEdit(self.BaseWidget)
        self.functionInput_2.setGeometry(QtCore.QRect(150, 120, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.functionInput_2.setFont(font)
        self.functionInput_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 13pt \"Segoe Print\";")
        self.functionInput_2.setInputMask("")
        self.functionInput_2.setMaxLength(32766)
        self.functionInput_2.setObjectName("functionInput_2")
        self.leftBorderInput = QtWidgets.QLineEdit(self.BaseWidget)
        self.leftBorderInput.setGeometry(QtCore.QRect(170, 240, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.leftBorderInput.setFont(font)
        self.leftBorderInput.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 13pt \"Segoe Print\";")
        self.leftBorderInput.setInputMask("")
        self.leftBorderInput.setMaxLength(32766)
        self.leftBorderInput.setObjectName("leftBorderInput")
        self.rightBorderInput = QtWidgets.QLineEdit(self.BaseWidget)
        self.rightBorderInput.setGeometry(QtCore.QRect(350, 240, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rightBorderInput.setFont(font)
        self.rightBorderInput.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 13pt \"Segoe Print\";")
        self.rightBorderInput.setInputMask("")
        self.rightBorderInput.setMaxLength(32766)
        self.rightBorderInput.setObjectName("rightBorderInput")
        self.INFORMATION = QtWidgets.QLabel(self.BaseWidget)
        self.INFORMATION.setGeometry(QtCore.QRect(80, 20, 451, 291))
        self.INFORMATION.setStyleSheet("font: 13pt \"Segoe Print\";")
        self.INFORMATION.setTextFormat(QtCore.Qt.PlainText)
        self.INFORMATION.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.INFORMATION.setObjectName("INFORMATION")
        self.messageBox = QtWidgets.QLabel(self.BaseWidget)
        self.messageBox.setGeometry(QtCore.QRect(20, 320, 511, 231))
        self.messageBox.setStyleSheet("font: 87 10pt \"Segoe UI\";")
        self.messageBox.setText("")
        self.messageBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.messageBox.setObjectName("messageBox")
        self.goBackButton = QtWidgets.QLabel(self.BaseWidget)
        self.goBackButton.setGeometry(QtCore.QRect(4, 10, 61, 51))
        self.goBackButton.setText("")
        self.goBackButton.setPixmap(QtGui.QPixmap("goBack.png"))
        self.goBackButton.setObjectName("goBackButton")
        self.INFORMATION.raise_()
        self.functionInput.raise_()
        self.askButton.raise_()
        self.functionInput_2.raise_()
        self.leftBorderInput.raise_()
        self.rightBorderInput.raise_()
        self.messageBox.raise_()
        self.calcButton.raise_()
        self.goBackButton.raise_()
        BaseWindow.setCentralWidget(self.BaseWidget)

        self.retranslateUi(BaseWindow)
        QtCore.QMetaObject.connectSlotsByName(BaseWindow)

    def retranslateUi(self, BaseWindow):
        _translate = QtCore.QCoreApplication.translate
        BaseWindow.setWindowTitle(_translate("BaseWindow", "WorkRaum"))
        self.functionInput.setWhatsThis(_translate("BaseWindow", "<html><head/><body><p>Введите формулу. Если не знаете как, посмотрите во вкладке &quot;Помощь&quot;</p></body></html>"))
        self.calcButton.setWhatsThis(_translate("BaseWindow", "<html><head/><body><p>Показать график</p></body></html>"))
        self.functionInput_2.setWhatsThis(_translate("BaseWindow", "<html><head/><body><p>Введите формулу. Если не знаете как, посмотрите во вкладке &quot;Помощь&quot;</p></body></html>"))
        self.leftBorderInput.setWhatsThis(_translate("BaseWindow", "<html><head/><body><p>Левая граница области определения (минимальное значение x)</p></body></html>"))
        self.rightBorderInput.setWhatsThis(_translate("BaseWindow", "<html><head/><body><p>Правая граница области определения (максимальный x)</p></body></html>"))
        self.INFORMATION.setText(_translate("BaseWindow", "y1 =\n"
"  \n"
"\n"
"y2 =\n"
"\n"
"\n"
"x ∈  (                  ;                     )"))
