# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NotesWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotesWindow(object):
    def setupUi(self, NotesWindow):
        NotesWindow.setObjectName("NotesWindow")
        NotesWindow.resize(950, 650)
        NotesWindow.setMinimumSize(QtCore.QSize(950, 650))
        NotesWindow.setMaximumSize(QtCore.QSize(950, 16777215))
        NotesWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BaseWidget = QtWidgets.QWidget(NotesWindow)
        self.BaseWidget.setStyleSheet("background-color: rgb(250, 245, 230);")
        self.BaseWidget.setObjectName("BaseWidget")
        self.goBackButton = QtWidgets.QLabel(self.BaseWidget)
        self.goBackButton.setGeometry(QtCore.QRect(10, 0, 61, 71))
        self.goBackButton.setText("")
        self.goBackButton.setPixmap(QtGui.QPixmap("ui/ui/goBack.png"))
        self.goBackButton.setObjectName("goBackButton")
        self.removeButton = QtWidgets.QLabel(self.BaseWidget)
        self.removeButton.setGeometry(QtCore.QRect(10, 160, 61, 71))
        self.removeButton.setText("")
        self.removeButton.setPixmap(QtGui.QPixmap("ui/ui/binIcon.png"))
        self.removeButton.setObjectName("removeButton")
        self.exportButton = QtWidgets.QLabel(self.BaseWidget)
        self.exportButton.setGeometry(QtCore.QRect(10, 240, 61, 71))
        self.exportButton.setText("")
        self.exportButton.setPixmap(QtGui.QPixmap("ui/ui/exportIcon.png"))
        self.exportButton.setObjectName("exportButton")
        self.addButton = QtWidgets.QLabel(self.BaseWidget)
        self.addButton.setGeometry(QtCore.QRect(10, 80, 61, 71))
        self.addButton.setText("")
        self.addButton.setPixmap(QtGui.QPixmap("ui/ui/addIcon.png"))
        self.addButton.setObjectName("addButton")
        self.listWidget = QtWidgets.QListWidget(self.BaseWidget)
        self.listWidget.setGeometry(QtCore.QRect(90, 10, 841, 621))
        self.listWidget.setObjectName("listWidget")
        NotesWindow.setCentralWidget(self.BaseWidget)

        self.retranslateUi(NotesWindow)
        QtCore.QMetaObject.connectSlotsByName(NotesWindow)

    def retranslateUi(self, NotesWindow):
        _translate = QtCore.QCoreApplication.translate
        NotesWindow.setWindowTitle(_translate("NotesWindow", "MainWindow"))
