# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ToDoMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToDoMenu(object):
    def setupUi(self, ToDoMenu):
        ToDoMenu.setObjectName("ToDoMenu")
        ToDoMenu.resize(950, 650)
        ToDoMenu.setMinimumSize(QtCore.QSize(950, 650))
        ToDoMenu.setMaximumSize(QtCore.QSize(950, 16777215))
        ToDoMenu.setMouseTracking(False)
        ToDoMenu.setLayoutDirection(QtCore.Qt.LeftToRight)
        ToDoMenu.setStyleSheet("background-color: rgb(23, 28, 37);\n"
"color: rgb(255, 255, 255);")
        self.BaseWidget = QtWidgets.QWidget(ToDoMenu)
        self.BaseWidget.setStyleSheet("background-color: rgb(23, 28, 37);")
        self.BaseWidget.setObjectName("BaseWidget")
        self.goToNotes = QtWidgets.QLabel(self.BaseWidget)
        self.goToNotes.setGeometry(QtCore.QRect(10, 40, 71, 71))
        self.goToNotes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.goToNotes.setText("")
        self.goToNotes.setPixmap(QtGui.QPixmap("ui/notesIcon.png"))
        self.goToNotes.setObjectName("goToNotes")
        self.removeButton = QtWidgets.QLabel(self.BaseWidget)
        self.removeButton.setGeometry(QtCore.QRect(10, 300, 71, 71))
        self.removeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.removeButton.setText("")
        self.removeButton.setPixmap(QtGui.QPixmap("ui/binIcon.png"))
        self.removeButton.setObjectName("removeButton")
        self.exportButton = QtWidgets.QLabel(self.BaseWidget)
        self.exportButton.setGeometry(QtCore.QRect(10, 390, 71, 71))
        self.exportButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exportButton.setText("")
        self.exportButton.setPixmap(QtGui.QPixmap("ui/exportIcon.png"))
        self.exportButton.setObjectName("exportButton")
        self.addButton = QtWidgets.QLabel(self.BaseWidget)
        self.addButton.setGeometry(QtCore.QRect(10, 210, 71, 71))
        self.addButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addButton.setText("")
        self.addButton.setPixmap(QtGui.QPixmap("ui/addIcon.png"))
        self.addButton.setObjectName("addButton")
        self.tableWidget = QtWidgets.QTableWidget(self.BaseWidget)
        self.tableWidget.setGeometry(QtCore.QRect(90, 40, 841, 601))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("font: 18pt \"Segoe UI\";\n"
"color: rgb(14, 23, 38);\n"
"background-color: rgb(14, 23, 38);")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(10)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.titleBar = QtWidgets.QWidget(self.BaseWidget)
        self.titleBar.setGeometry(QtCore.QRect(-3, -10, 961, 41))
        self.titleBar.setMouseTracking(False)
        self.titleBar.setStyleSheet("background-color: rgb(35, 41, 53);")
        self.titleBar.setObjectName("titleBar")
        self.closeButton = QtWidgets.QPushButton(self.titleBar)
        self.closeButton.setGeometry(QtCore.QRect(920, 7, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(12)
        self.closeButton.setFont(font)
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setMouseTracking(False)
        self.closeButton.setStyleSheet("QPushButton::hover\n"
"{\n"
"    background-color : red;\n"
" }")
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName("closeButton")
        self.hideButton = QtWidgets.QPushButton(self.titleBar)
        self.hideButton.setGeometry(QtCore.QRect(890, 7, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(12)
        self.hideButton.setFont(font)
        self.hideButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hideButton.setFlat(True)
        self.hideButton.setObjectName("hideButton")
        self.calendarButton = QtWidgets.QLabel(self.BaseWidget)
        self.calendarButton.setGeometry(QtCore.QRect(10, 130, 71, 71))
        self.calendarButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calendarButton.setText("")
        self.calendarButton.setPixmap(QtGui.QPixmap("ui/calendarIcon.png"))
        self.calendarButton.setObjectName("calendarButton")
        self.settingsButton = QtWidgets.QLabel(self.BaseWidget)
        self.settingsButton.setGeometry(QtCore.QRect(10, 480, 71, 71))
        self.settingsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingsButton.setText("")
        self.settingsButton.setPixmap(QtGui.QPixmap("ui/settingsIcon.png"))
        self.settingsButton.setObjectName("settingsButton")
        self.askButton = QtWidgets.QLabel(self.BaseWidget)
        self.askButton.setGeometry(QtCore.QRect(10, 570, 71, 71))
        self.askButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.askButton.setText("")
        self.askButton.setPixmap(QtGui.QPixmap("ui/questionIcon.png"))
        self.askButton.setObjectName("askButton")
        ToDoMenu.setCentralWidget(self.BaseWidget)

        self.retranslateUi(ToDoMenu)
        QtCore.QMetaObject.connectSlotsByName(ToDoMenu)

    def retranslateUi(self, ToDoMenu):
        _translate = QtCore.QCoreApplication.translate
        ToDoMenu.setWindowTitle(_translate("ToDoMenu", "MainWindow"))
        self.tableWidget.setSortingEnabled(False)
        self.closeButton.setText(_translate("ToDoMenu", "r"))
        self.hideButton.setText(_translate("ToDoMenu", "0"))
