# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ToDoWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToDoWindow(object):
    def setupUi(self, ToDoWindow):
        ToDoWindow.setObjectName("ToDoWindow")
        ToDoWindow.resize(525, 380)
        ToDoWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        ToDoWindow.setStyleSheet("font: 8pt \"Segoe UI\";")
        self.ToDoWidget = QtWidgets.QWidget(ToDoWindow)
        self.ToDoWidget.setStyleSheet("background-color: rgb(23, 28, 37);")
        self.ToDoWidget.setObjectName("ToDoWidget")
        self.spacer = QtWidgets.QWidget(self.ToDoWidget)
        self.spacer.setGeometry(QtCore.QRect(-9, -5, 541, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spacer.sizePolicy().hasHeightForWidth())
        self.spacer.setSizePolicy(sizePolicy)
        self.spacer.setMinimumSize(QtCore.QSize(351, 25))
        self.spacer.setStyleSheet("background-color: rgb(50, 130, 184);")
        self.spacer.setObjectName("spacer")
        self.infoEdit = QtWidgets.QTextEdit(self.ToDoWidget)
        self.infoEdit.setGeometry(QtCore.QRect(85, 200, 431, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoEdit.sizePolicy().hasHeightForWidth())
        self.infoEdit.setSizePolicy(sizePolicy)
        self.infoEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.infoEdit.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: rgb(50, 130, 184);\n"
"background-color: rgb(14, 23, 38);\n"
"")
        self.infoEdit.setObjectName("infoEdit")
        self.nameInput = QtWidgets.QLineEdit(self.ToDoWidget)
        self.nameInput.setGeometry(QtCore.QRect(88, 50, 431, 40))
        self.nameInput.setMaximumSize(QtCore.QSize(16777215, 40))
        self.nameInput.setStyleSheet("font: 87 italic 12pt \"Segoe UI Black\";\n"
"alternate-background-color: rgb(15, 76, 117);\n"
"color: rgb(50, 130, 184);\n"
"background-color: rgb(14, 23, 38);\n"
"border-color: rgb(15, 76, 117);")
        self.nameInput.setText("")
        self.nameInput.setMaxLength(100)
        self.nameInput.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.nameInput.setObjectName("nameInput")
        self.deadlineBox = QtWidgets.QCheckBox(self.ToDoWidget)
        self.deadlineBox.setGeometry(QtCore.QRect(90, 100, 101, 31))
        self.deadlineBox.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: rgb(50, 130, 184);")
        self.deadlineBox.setObjectName("deadlineBox")
        self.dateEdit = QtWidgets.QDateEdit(self.ToDoWidget)
        self.dateEdit.setEnabled(False)
        self.dateEdit.setGeometry(QtCore.QRect(260, 100, 251, 31))
        self.dateEdit.setStyleSheet("color: rgb(50, 130, 184);\n"
"font: 12pt \"Segoe UI\";")
        self.dateEdit.setMinimumDate(QtCore.QDate(2004, 1, 6))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.goBackButton = QtWidgets.QLabel(self.ToDoWidget)
        self.goBackButton.setGeometry(QtCore.QRect(10, 40, 71, 71))
        self.goBackButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.goBackButton.setText("")
        self.goBackButton.setPixmap(QtGui.QPixmap("ui/goBackIcon.png"))
        self.goBackButton.setObjectName("goBackButton")
        self.doneButton = QtWidgets.QLabel(self.ToDoWidget)
        self.doneButton.setGeometry(QtCore.QRect(10, 120, 71, 71))
        self.doneButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doneButton.setText("")
        self.doneButton.setPixmap(QtGui.QPixmap("ui/doneIcon.png"))
        self.doneButton.setObjectName("doneButton")
        self.colorBox = QtWidgets.QComboBox(self.ToDoWidget)
        self.colorBox.setGeometry(QtCore.QRect(260, 150, 251, 31))
        self.colorBox.setStyleSheet("color: rgb(50, 130, 184);\n"
"font: 12pt \"Segoe UI\";")
        self.colorBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.colorBox.setFrame(False)
        self.colorBox.setObjectName("colorBox")
        self.colorBox.addItem("")
        self.colorBox.addItem("")
        self.colorBox.addItem("")
        self.colorBox.addItem("")
        self.label = QtWidgets.QLabel(self.ToDoWidget)
        self.label.setGeometry(QtCore.QRect(90, 150, 161, 31))
        self.label.setStyleSheet("color: rgb(50, 130, 184);\n"
"font: 12pt \"Segoe UI\";")
        self.label.setObjectName("label")
        ToDoWindow.setCentralWidget(self.ToDoWidget)

        self.retranslateUi(ToDoWindow)
        QtCore.QMetaObject.connectSlotsByName(ToDoWindow)

    def retranslateUi(self, ToDoWindow):
        _translate = QtCore.QCoreApplication.translate
        ToDoWindow.setWindowTitle(_translate("ToDoWindow", "MainWindow"))
        self.deadlineBox.setText(_translate("ToDoWindow", "Дедлайн"))
        self.colorBox.setItemText(0, _translate("ToDoWindow", "Синий"))
        self.colorBox.setItemText(1, _translate("ToDoWindow", "Жёлтый"))
        self.colorBox.setItemText(2, _translate("ToDoWindow", "Зелёный"))
        self.colorBox.setItemText(3, _translate("ToDoWindow", "Фиолетовый"))
        self.label.setText(_translate("ToDoWindow", "Выберите цвет:"))
