# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalendarWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalendarWindow(object):
    def setupUi(self, CalendarWindow):
        CalendarWindow.setObjectName("CalendarWindow")
        CalendarWindow.resize(690, 488)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        CalendarWindow.setFont(font)
        CalendarWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        CalendarWindow.setStyleSheet("font: 8pt \"Segoe UI\";")
        self.CalendawWidget = QtWidgets.QWidget(CalendarWindow)
        self.CalendawWidget.setStyleSheet("background-color: rgb(23, 28, 37);")
        self.CalendawWidget.setObjectName("CalendawWidget")
        self.titleBar = QtWidgets.QWidget(self.CalendawWidget)
        self.titleBar.setGeometry(QtCore.QRect(0, 0, 691, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleBar.sizePolicy().hasHeightForWidth())
        self.titleBar.setSizePolicy(sizePolicy)
        self.titleBar.setMinimumSize(QtCore.QSize(0, 41))
        self.titleBar.setMaximumSize(QtCore.QSize(16777215, 41))
        self.titleBar.setMouseTracking(False)
        self.titleBar.setStyleSheet("background-color: rgb(35, 41, 53);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Webdings\";")
        self.titleBar.setObjectName("titleBar")
        self.closeButton = QtWidgets.QPushButton(self.titleBar)
        self.closeButton.setGeometry(QtCore.QRect(660, 7, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(12)
        self.closeButton.setFont(font)
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setMouseTracking(False)
        self.closeButton.setStyleSheet("QPushButton::hover\n"
"{\n"
"    background-color : red;\n"
" }")
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName("closeButton")
        self.hideButton = QtWidgets.QPushButton(self.titleBar)
        self.hideButton.setGeometry(QtCore.QRect(630, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(12)
        self.hideButton.setFont(font)
        self.hideButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hideButton.setFlat(True)
        self.hideButton.setObjectName("hideButton")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.CalendawWidget)
        self.calendarWidget.setGeometry(QtCore.QRect(11, 59, 661, 421))
        self.calendarWidget.setStyleSheet("alternate-background-color: rgb(50, 130, 184);\n"
"color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(237, 250, 255);\n"
"selection-color: rgb(35, 41, 53);")
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setObjectName("calendarWidget")
        CalendarWindow.setCentralWidget(self.CalendawWidget)

        self.retranslateUi(CalendarWindow)
        QtCore.QMetaObject.connectSlotsByName(CalendarWindow)

    def retranslateUi(self, CalendarWindow):
        _translate = QtCore.QCoreApplication.translate
        CalendarWindow.setWindowTitle(_translate("CalendarWindow", "MainWindow"))
        self.closeButton.setText(_translate("CalendarWindow", "r"))
        self.hideButton.setText(_translate("CalendarWindow", "0"))
