# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NotesMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotesMenu(object):
    def setupUi(self, NotesMenu):
        NotesMenu.setObjectName("NotesMenu")
        NotesMenu.resize(950, 650)
        NotesMenu.setMinimumSize(QtCore.QSize(950, 650))
        NotesMenu.setMaximumSize(QtCore.QSize(950, 16777215))
        NotesMenu.setLayoutDirection(QtCore.Qt.LeftToRight)
        NotesMenu.setStyleSheet("background-color: rgb(23, 28, 37);\n"
"color: rgb(255, 255, 255);")
        self.BaseWidget = QtWidgets.QWidget(NotesMenu)
        self.BaseWidget.setStyleSheet("background-color: rgb(23, 28, 37);")
        self.BaseWidget.setObjectName("BaseWidget")
        self.goToToDo = QtWidgets.QLabel(self.BaseWidget)
        self.goToToDo.setGeometry(QtCore.QRect(10, 40, 71, 71))
        self.goToToDo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.goToToDo.setText("")
        self.goToToDo.setPixmap(QtGui.QPixmap("ui/ToDoIcon.png"))
        self.goToToDo.setObjectName("goToToDo")
        self.removeButton = QtWidgets.QLabel(self.BaseWidget)
        self.removeButton.setGeometry(QtCore.QRect(10, 220, 71, 71))
        self.removeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.removeButton.setText("")
        self.removeButton.setPixmap(QtGui.QPixmap("ui/binIcon.png"))
        self.removeButton.setObjectName("removeButton")
        self.exportButton = QtWidgets.QLabel(self.BaseWidget)
        self.exportButton.setGeometry(QtCore.QRect(10, 310, 71, 71))
        self.exportButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exportButton.setText("")
        self.exportButton.setPixmap(QtGui.QPixmap("ui/exportIcon.png"))
        self.exportButton.setObjectName("exportButton")
        self.addButton = QtWidgets.QLabel(self.BaseWidget)
        self.addButton.setGeometry(QtCore.QRect(10, 130, 71, 71))
        self.addButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addButton.setText("")
        self.addButton.setPixmap(QtGui.QPixmap("ui/addIcon.png"))
        self.addButton.setObjectName("addButton")
        self.listWidget = QtWidgets.QListWidget(self.BaseWidget)
        self.listWidget.setGeometry(QtCore.QRect(90, 40, 841, 601))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("font: 18pt \"Segoe UI\";\n"
"color: rgb(50, 130, 184);\n"
"background-color: rgb(14, 23, 38);")
        self.listWidget.setObjectName("listWidget")
        self.titleBar = QtWidgets.QWidget(self.BaseWidget)
        self.titleBar.setGeometry(QtCore.QRect(-3, -10, 961, 41))
        self.titleBar.setMouseTracking(False)
        self.titleBar.setStyleSheet("background-color: rgb(35, 41, 53);")
        self.titleBar.setObjectName("titleBar")
        self.closeButton = QtWidgets.QPushButton(self.titleBar)
        self.closeButton.setGeometry(QtCore.QRect(920, 7, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(12)
        self.closeButton.setFont(font)
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setMouseTracking(False)
        self.closeButton.setStyleSheet("QPushButton::hover\n"
"{\n"
"    background-color : red;\n"
" }")
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName("closeButton")
        self.hideButton = QtWidgets.QPushButton(self.titleBar)
        self.hideButton.setGeometry(QtCore.QRect(890, 7, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(12)
        self.hideButton.setFont(font)
        self.hideButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hideButton.setFlat(True)
        self.hideButton.setObjectName("hideButton")
        self.askButton = QtWidgets.QLabel(self.BaseWidget)
        self.askButton.setGeometry(QtCore.QRect(10, 400, 71, 71))
        self.askButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.askButton.setText("")
        self.askButton.setPixmap(QtGui.QPixmap("ui/questionIcon.png"))
        self.askButton.setObjectName("askButton")
        NotesMenu.setCentralWidget(self.BaseWidget)

        self.retranslateUi(NotesMenu)
        QtCore.QMetaObject.connectSlotsByName(NotesMenu)

    def retranslateUi(self, NotesMenu):
        _translate = QtCore.QCoreApplication.translate
        NotesMenu.setWindowTitle(_translate("NotesMenu", "MainWindow"))
        self.closeButton.setText(_translate("NotesMenu", "r"))
        self.hideButton.setText(_translate("NotesMenu", "0"))
