# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NotesWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotesWindow(object):
    def setupUi(self, NotesWindow):
        NotesWindow.setObjectName("NotesWindow")
        NotesWindow.resize(950, 650)
        NotesWindow.setMinimumSize(QtCore.QSize(950, 650))
        NotesWindow.setMaximumSize(QtCore.QSize(950, 16777215))
        NotesWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        NotesWindow.setStyleSheet("background-color: rgb(23, 28, 37);\n"
"color: rgb(255, 255, 255);")
        self.BaseWidget = QtWidgets.QWidget(NotesWindow)
        self.BaseWidget.setStyleSheet("background-color: rgb(23, 28, 37);")
        self.BaseWidget.setObjectName("BaseWidget")
        self.goBackButton = QtWidgets.QLabel(self.BaseWidget)
        self.goBackButton.setGeometry(QtCore.QRect(10, 40, 71, 71))
        self.goBackButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.goBackButton.setText("")
        self.goBackButton.setPixmap(QtGui.QPixmap("ui/goBackIcon.png"))
        self.goBackButton.setObjectName("goBackButton")
        self.removeButton = QtWidgets.QLabel(self.BaseWidget)
        self.removeButton.setGeometry(QtCore.QRect(10, 200, 71, 71))
        self.removeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.removeButton.setText("")
        self.removeButton.setPixmap(QtGui.QPixmap("ui/binIcon.png"))
        self.removeButton.setObjectName("removeButton")
        self.exportButton = QtWidgets.QLabel(self.BaseWidget)
        self.exportButton.setGeometry(QtCore.QRect(10, 280, 71, 71))
        self.exportButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exportButton.setText("")
        self.exportButton.setPixmap(QtGui.QPixmap("ui/exportIcon.png"))
        self.exportButton.setObjectName("exportButton")
        self.addButton = QtWidgets.QLabel(self.BaseWidget)
        self.addButton.setGeometry(QtCore.QRect(10, 120, 71, 71))
        self.addButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addButton.setText("")
        self.addButton.setPixmap(QtGui.QPixmap("ui/addIcon.png"))
        self.addButton.setObjectName("addButton")
        self.listWidget = QtWidgets.QListWidget(self.BaseWidget)
        self.listWidget.setGeometry(QtCore.QRect(90, 40, 841, 601))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("font: 18pt \"Segoe UI\";\n"
"color: rgb(50, 130, 184);\n"
"background-color: rgb(14, 23, 38);")
        self.listWidget.setObjectName("listWidget")

        NotesWindow.setCentralWidget(self.BaseWidget)

        self.retranslateUi(NotesWindow)
        QtCore.QMetaObject.connectSlotsByName(NotesWindow)

    def retranslateUi(self, NotesWindow):
        _translate = QtCore.QCoreApplication.translate
        NotesWindow.setWindowTitle(_translate("NotesWindow", "MainWindow"))
        self.closeButton.setText(_translate("NotesWindow", "r"))
        self.hideButton.setText(_translate("NotesWindow", "0"))
